class Country < ActiveHash::Base
  self.data = [
    { id: 1,  name: '--', area: '--', image:"" },
    { id: 2,  name: 'ベトナム', area: 'アジア', image:"" },
    { id: 3,  name: 'フィリピン', area: 'アジア', image:"" },
    { id: 4,  name: 'インドネシア', area: 'アジア', image:"" },
    { id: 5,  name: 'インド', area: 'アジア', image:"" },
    { id: 6,  name: 'イエメン', area: 'アジア', image:"" },
    { id: 7,  name: 'エチオピア', area: 'アフリカ', image:"" },
    { id: 8,  name: 'ルワンダ', area: 'アフリカ', image:"" },
    { id: 9,  name: 'ケニア', area: 'アフリカ', image:"" },
    { id: 10,  name: 'タンザニア', area: 'アフリカ', image:"" },
    { id: 11, name: 'ウガンダ', area: 'アフリカ', image:"" },
    { id: 12, name: 'ブラジル', area: '南アメリカ', image:"" },
    { id: 13, name: 'コロンビア', area: '南アメリカ', image:"" },
    { id: 14, name: 'ペルー', area: '南アメリカ', image:"" },
    { id: 15, name: 'ドミニカ共和国', area: '中央アメリカ', image:"" },
    { id: 16, name: 'ジャマイカ', area: '中央アメリカ', image:"" },
    { id: 17, name: 'ニカラグア', area: '中央アメリカ', image:"" },
    { id: 18, name: 'コスタリカ', area: '中央アメリカ', image:"" },
    { id: 19, name: 'ホンジュラス', area: '中央アメリカ', image:"" },
    { id: 20, name: 'エルサルバドル', area: '中央アメリカ', image:"" },
    { id: 21, name: 'グァテマラ', area: '中央アメリカ', image:"" },
    { id: 22, name: 'アメリカ', area: '北アメリカ', image:"" },
  ]
end
